### ISSUE TITLE
Making it clear when a link takes you away from pyaos.github.io

### ISSUE THREAD

**Issue by soto97** [PyAOS/pyaos.github.io#2]
I like what you are doing with the new site and the attempt to make it more community oriented. To help with this, I think you need to make it clearer when someone leaves the PyAOS site for your personal site. Right now, when I click on "about the author" it took me a moment to see that I had left PyAOS. It's *nothing critical*, but I would at least change the color schemes on one of the sites to make the difference more obvious.

**Comment by DamienIrving** [comment]
Good idea, @soto97. (You spotted my laziness in using exactly the same Jekyll template for my personal website and the PyAOS site!)

I've altered the background color on my personal site.
