### ISSUE TITLE
Add xmovie?

### ISSUE THREAD

**Issue by aidanheerdegen** [PyAOS/pyaos.github.io#8]
The [xmovie package](https://github.com/jbusecke/xmovie) by Julius Busecke seems really useful, without succumbing to feature creep

https://xmovie.readthedocs.io/en/latest/

I had thought of [adding it directly to ACCESS-Hive](https://github.com/ACCESS-Hive/access-hive.github.io/issues/182) but I think it probably should be linked by a catalogue such as this.

What do you reckon @DamienIrving ?

**Comment by DamienIrving** [comment]
I reckon that's a good addition. A general movie making package would be out of scope, but this one is written by someone in the PyAOS community and all the examples in the documentation are geared towards PyAOS problems. I've added it in https://github.com/PyAOS/pyaos.github.io/commit/7b83df09ac85fce5a3cdb73f193e30705634bf13.
